"""FASE 11 + FASE 13 — HTTP application factory.

Boundary: ``/v1``. Every command endpoint translates HTTP -> Command and delegates
to the ``CommandGateway`` (-> CommandRunner -> handlers). No business logic, no
concrete repositories, no SQLite, no aggregates live here. Contract validation is
NOT re-implemented: the versioned JSON-Schemas remain the single source of truth
(validated by the Application's ``contract_validated`` decorator).

Security (FASE 13): the client NEVER declares its role. An ``AuthenticationProvider``
establishes the principal (identity + role) from a real credential; the role is
then authorized per-command before the request reaches the gateway. The domain
``Actor`` is derived from the authenticated principal, so ``role=admin`` cannot be
forged in the request body or command payload.
"""

from __future__ import annotations

import os
import uuid
from contextlib import asynccontextmanager
from typing import Any, Dict, Optional

from fastapi import FastAPI, Request
from pydantic import BaseModel, Field

from ..application.commands.commands import COMMANDS
from ..application.validation import ContractValidationError, load_schema
from ..domain.common import DomainError
from ..domain.errors import EntityNotFound, MatchNotFound
from ..infrastructure.logging import Logger, StdLogger
from ..infrastructure.persistence.errors import (
    InfrastructureError,
    SerializationConflictError,
    StaleVersionError,
)
from . import errors as err
from .analytics import register_analytics_routes
from .auth import (
    AuthenticationProvider,
    ApiKeyAuthenticationProvider,
    is_authorized,
)
from .exploration import (
    register_exploration_profile_routes,
    register_exploration_search_routes,
)
from .gateway import CommandGateway
from .middleware import DEFAULT_BODY_LIMIT, RequestContextMiddleware, RequestLogger

APP_VERSION = "1.0.0"

API_DESCRIPTION = (
    "feb_score HTTP API — boundary over the Application layer.\n\n"
    "Authentication: commands require an API key (Authorization: Bearer <key> or "
    "X-API-Key). The role is derived from the key, never from the request body. "
    "Reads, contracts, /health and /ready are public.\n\n"
    "Versioning: the API is versioned under `/v1`; the command contracts are the "
    "versioned JSON-Schemas served at `GET /v1/contracts/{command_type}` and remain "
    "the single source of truth for payload validation (contract version and API "
    "version evolve independently).\n\n"
    "Every `POST /v1/commands/{command_type}` runs the command in ONE transaction "
    "(state + events + idempotency) via the CommandRunner. The response never marks "
    "events delivered: persistence and dispatch are separate responsibilities "
    "(outbox semantics)."
)


class CommandRequest(BaseModel):
    """HTTP envelope for a command. `payload` is validated against the command's
    versioned JSON-Schema by the Application layer, not here.

    FASE 13: there is NO client-declared actor/role in the envelope; identity and
    role come exclusively from the authenticated principal.
    """

    model_config = {"extra": "forbid"}

    command_id: Optional[str] = Field(
        default=None,
        description="Idempotency key; generated by the server if absent.",
    )
    payload: Dict[str, Any] = Field(
        ...,
        description="Command payload. Schema: GET /v1/contracts/{command_type}",
    )


def create_app(
    gateway: CommandGateway,
    *,
    auth: Optional[AuthenticationProvider] = None,
    logger: Optional[Logger] = None,
    body_size_limit: int = DEFAULT_BODY_LIMIT,
    rate_limiter=None,
) -> FastAPI:
    base_logger = logger or StdLogger("feb_score.api")
    request_logger = RequestLogger(base_logger)

    @asynccontextmanager
    async def _lifespan(_app: FastAPI):
        # FASE 13 — graceful shutdown seam: startup/shutdown are observable and
        # testable. feb_score keeps no background workers and no connection pool,
        # so shutdown cannot drop in-flight transactions or leave connections open
        # (Uvicorn finishes active requests before running shutdown).
        request_logger.log("info", "app_startup")
        yield
        request_logger.log("info", "app_shutdown")

    app = FastAPI(
        title="feb_score API",
        version=APP_VERSION,
        description=API_DESCRIPTION,
        docs_url="/docs"
        if os.environ.get("FEB_SCORE_DISABLE_DOCS", "").lower() not in {"1", "true", "yes"}
        else None,
        redoc_url=None,
        openapi_url=None
        if os.environ.get("FEB_SCORE_DISABLE_DOCS", "").lower() in {"1", "true", "yes"}
        else "/openapi.json",
        lifespan=_lifespan,
    )
    app.state.gateway = gateway
    app.state.logger = request_logger
    app.state.auth = auth or ApiKeyAuthenticationProvider({})

    app.add_middleware(
        RequestContextMiddleware,
        body_size_limit=body_size_limit,
        rate_limiter=rate_limiter,
    )
    err.register_error_handlers(app, request_logger)

    # FASE 24 route order matters: the literal /search paths must beat the
    # {external_id} parameter routes, and the analytics /leaderboards and
    # /metrics literals must beat the {player_external_id} profile route.
    register_exploration_search_routes(app)
    _register_routes(app)
    register_analytics_routes(app)
    register_exploration_profile_routes(app)
    return app


def _principal_actor(request: Request, command_type: str):
    """Authenticate + authorize a command; returns (actor_dict, error_tuple)."""
    auth: AuthenticationProvider = request.app.state.auth
    principal = auth.authenticate(request)
    if principal is None:
        return None, (401, "UNAUTHENTICATED", "missing or invalid API key; commands require authentication")
    if not is_authorized(command_type, principal):
        return None, (
            403,
            "FORBIDDEN",
            f"principal {principal.id} (role {principal.role}) cannot run command {command_type}",
        )
    return {"id": principal.id, "role": principal.role}, None


def _register_routes(app: FastAPI) -> None:
    # ------------------------------------------------------------- commands
    @app.post(
        "/v1/commands/{command_type}",
        tags=["commands"],
        summary="Execute a command",
        description="Executes the named command through the CommandRunner in a single "
        "transaction. `command_id` is the idempotency key: replaying it produces no "
        "duplicate state or events. Requires an authenticated API key with a role "
        "sufficient for the command.",
    )
    def post_command(command_type: str, body: CommandRequest, request: Request):
        gateway: CommandGateway = request.app.state.gateway
        command_id = body.command_id or str(uuid.uuid4())

        if command_type not in COMMANDS:
            return err.error_response(
                404, "UNKNOWN_COMMAND", f"unknown command: {command_type}", command_id=command_id
            )

        actor, auth_error = _principal_actor(request, command_type)
        if auth_error is not None:
            status, code, message = auth_error
            return err.error_response(status, code, message, command_id=command_id)

        try:
            result = gateway.run(command_type, command_id=command_id, actor=actor, payload=body.payload)
        except ContractValidationError as exc:
            return err.error_response(422, "CONTRACT_VALIDATION", str(exc), command_id=command_id)
        except (MatchNotFound, EntityNotFound) as exc:
            return err.error_response(404, "NOT_FOUND", str(exc) or "entity not found", command_id=command_id)
        except DomainError as exc:
            return err.map_domain_error(exc, command_id)
        except StaleVersionError:
            return err.error_response(
                409,
                "CONFLICT",
                "concurrent modification detected; retry with fresh data",
                command_id=command_id,
            )
        except SerializationConflictError:
            return err.error_response(
                409,
                "CONFLICT",
                "concurrent modification detected; retry with fresh data",
                command_id=command_id,
            )
        except InfrastructureError:
            return err.error_response(
                503, "INFRASTRUCTURE_UNAVAILABLE", "storage temporarily unavailable", command_id=command_id
            )
        except ValueError as exc:
            # Command envelope construction failure (e.g. unknown actor role).
            return err.error_response(422, "CONTRACT_VALIDATION", str(exc), command_id=command_id)

        return {
            "command_id": result.command_id,
            "status": "accepted",
            "events": [{"event_id": e.event_id, "event_type": e.event_type} for e in result.events],
        }

    # ------------------------------------------------------------- reads
    @app.get("/v1/matches/{external_id}", tags=["reads"], summary="Get a match by external id")
    def get_match(external_id: str, request: Request):
        dto = request.app.state.gateway.get_match(external_id)
        if dto is None:
            return err.error_response(404, "NOT_FOUND", "match not found")
        return dto

    @app.get("/v1/players/{external_id}", tags=["reads"], summary="Get a player by external id")
    def get_player(external_id: str, request: Request):
        dto = request.app.state.gateway.get_player(external_id)
        if dto is None:
            return err.error_response(404, "NOT_FOUND", "player not found")
        return dto

    @app.get("/v1/teams/{external_id}", tags=["reads"], summary="Get a team by external id")
    def get_team(external_id: str, request: Request):
        dto = request.app.state.gateway.get_team(external_id)
        if dto is None:
            return err.error_response(404, "NOT_FOUND", "team not found")
        return dto

    @app.get("/v1/competitions/{external_id}", tags=["reads"], summary="Get a competition by external id")
    def get_competition(external_id: str, request: Request):
        dto = request.app.state.gateway.get_competition(external_id)
        if dto is None:
            return err.error_response(404, "NOT_FOUND", "competition not found")
        return dto

    @app.get("/v1/leaderboards/{leaderboard_id}", tags=["reads"], summary="Get a leaderboard by id")
    def get_leaderboard(leaderboard_id: str, request: Request):
        dto = request.app.state.gateway.get_leaderboard(leaderboard_id)
        if dto is None:
            return err.error_response(404, "NOT_FOUND", "leaderboard not found")
        return dto

    @app.get("/v1/correction-proposals/{proposal_id}", tags=["reads"], summary="Get a correction proposal")
    def get_correction_proposal(proposal_id: str, request: Request):
        dto = request.app.state.gateway.get_correction_proposal(proposal_id)
        if dto is None:
            return err.error_response(404, "NOT_FOUND", "correction proposal not found")
        return dto

    # ------------------------------------------------------------- contracts
    @app.get(
        "/v1/contracts/{command_type}",
        tags=["contracts"],
        summary="Versioned JSON-Schema contract for a command",
        description="Serves the exact JSON-Schema used to validate the command payload. "
        "This is the source of truth; the API performs no duplicate validation.",
    )
    def get_contract(command_type: str):
        try:
            return load_schema(f"commands/{command_type}.v1.json")
        except FileNotFoundError:
            return err.error_response(404, "UNKNOWN_CONTRACT", f"unknown contract: {command_type}")

    # ------------------------------------------------------------- system
    @app.get("/health", tags=["system"], summary="Liveness: the process is alive")
    def health():
        return {"status": "ok"}

    @app.get(
        "/ready",
        tags=["system"],
        summary="Readiness: dependencies are reachable",
        description="Non-destructive check: opens a connection, verifies the schema and "
        "confirms migrations are at the expected version. Distinguishes app-alive "
        "(/health) from dependency-health (/ready).",
    )
    def ready(request: Request):
        readiness = request.app.state.gateway.readiness()
        if readiness.ready:
            return {"status": "ready", "checks": readiness.checks}
        return err.error_response(
            503, "NOT_READY", "dependency check failed", details=readiness.checks
        )